import Foundation

/// Decoded form of Tests/LongitudeCoreTests/Fixtures/floor-contract.json, which
/// is generated by running the real web `getFloorForEnv` — see
/// Tools/FloorContract/README.md.
///
/// This lives in the test target on purpose: it is the shape of a fixture file,
/// not a shape the SDK ships.
struct FloorContract: Decodable {
    struct Source: Decodable {
        let baseJs: String
        let function: String
        let fileSha256: String
        let functionBodySha256: String
    }

    struct DeviceClass: Decodable {
        /// What base.js emits: "mobile" or "desktop".
        let web: String
        /// What the SDK must emit: "phone" or "tablet".
        let mobile: String
    }

    struct Input: Decodable {
        let platform: String
        let country: String
        let deviceClass: DeviceClass
        let section: String
        let sessionDepth: Int
        let uid: String
        /// Deliberately loose: one case sets a non-numeric baseFloor to pin
        /// `parseFloat(x) || 0`.
        let baseFloor: JSONValue
        let dynamicFloorsEnabled: Bool
        /// Object, null, or `{"$unparseable": true}`.
        let dynamicFloorParameters: JSONValue?
        /// Object, null, or `{"$unparseable": true}`. Keys may contain `{DC}`.
        let floors: JSONValue?
        let includeHighestBid: Bool
    }

    struct Case: Decodable {
        let name: String
        let why: String
        let ladderTier: String
        let input: Input
        /// The value the real web ladder returned. Usually a number; one case
        /// returns a string, which the app pipeline forbids upstream.
        let expected: JSONValue
        let expectedJSType: String
    }

    let source: Source
    let cases: [Case]

    static func load() throws -> FloorContract {
        guard let url = Bundle.module.url(
            forResource: "floor-contract", withExtension: "json"
        ) else {
            throw FixtureError.missing(
                "floor-contract.json is not in the test bundle. Check the "
                + "`resources: [.copy(...)]` entry in Package.swift."
            )
        }
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(FloorContract.self, from: data)
    }

    enum FixtureError: Error, CustomStringConvertible {
        case missing(String)
        var description: String {
            switch self {
            case .missing(let why): return why
            }
        }
    }
}

/// Minimal JSON value, because the fixtures intentionally contain
/// heterogeneously typed fields to pin the web ladder's loose typing. Using
/// `Double` throughout would erase exactly the cases worth testing.
enum JSONValue: Decodable, Equatable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case object([String: JSONValue])
    case array([JSONValue])
    case null

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() {
            self = .null
        } else if let b = try? c.decode(Bool.self) {
            self = .bool(b)
        } else if let d = try? c.decode(Double.self) {
            self = .number(d)
        } else if let s = try? c.decode(String.self) {
            self = .string(s)
        } else if let o = try? c.decode([String: JSONValue].self) {
            self = .object(o)
        } else if let a = try? c.decode([JSONValue].self) {
            self = .array(a)
        } else {
            throw DecodingError.dataCorruptedError(
                in: c, debugDescription: "unsupported JSON value"
            )
        }
    }

    var doubleValue: Double? {
        if case .number(let d) = self { return d }
        return nil
    }

    var stringValue: String? {
        if case .string(let s) = self { return s }
        return nil
    }

    var objectValue: [String: JSONValue]? {
        if case .object(let o) = self { return o }
        return nil
    }

    /// True for the `{"$unparseable": true}` sentinel the generator writes where
    /// the web side stored a string that is not valid JSON.
    var isUnparseableSentinel: Bool {
        objectValue?["$unparseable"] == .bool(true)
    }
}
